### ISSUE TITLE
RHEL8 rpm

### ISSUE THREAD

**Issue by shannonmitchell** [racker/rackspace-monitoring-poller#193]
Getting a package built for rhel8 and available at the following download page would be nice. 
 http://stable.poller.packages.cloudmonitoring.rackspace.com

**Comment by itzg** [comment]
I was about to say the RHEL7 RPM will work fine since the poller builds as a static executable; however, we would need to check if the correct init service is configured.

**Comment by itzg** [comment]
...looks like both upstart and systemd configs are bundled. Have you happened to see if the "RHEL7" RPM works as-is on RHEL8?

**Comment by shannonmitchell** [comment]
The binary seems to work fine.  I'm trying an rpc-maas install with some modifications now to make sure.  Would just be nice to have the repo to keep from doing any ansible hackery when using system vars to create the repo file.

**Comment by itzg** [comment]
Agreed, a RHEL8 specific repo URL would totally make sense. Your investigation helps a bunch to estimate the effort needed to get that positioned.

**Comment by shannonmitchell** [comment]
After a couple of config fixes and a full deploy of rpc-maas, the rhel7 binary works on rhel8 without issue.

**Comment by itzg** [comment]
I have opened a jira issue and tagged you on it @shannonmitchell
